name: Update Blog Posts

on:
  push:
    branches:
      - main
  schedule:
    - cron: '0 0 * * *'  # 매일 자정 UTC (한국 시간 오전 9시)
    - cron: '0 15 * * *' # 한국 시간 자정 (UTC 15:00)

jobs:
  update_blog:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: |
        pip install feedparser gitpython

    - name: Run script
      run: python scripts/update_blog.py

    - name: Commit and push changes
      run: |
        git config --global user.name 'sso'
        git config --global user.email 'soyeon3589@naver.com'
        git add .
        git commit -m "Update blog posts"
        git push

